### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shelld3v** [shelld3v/flydns#1]
- [ ] Fast (7/10)
- [x] Check for active subdomains
- [x] Recursion
- [ ] Minimum sub depth
- [x] Exclude subdomains by DNS answers
- [ ] Wildcard detection
- [ ] Support DNS servers list
- [ ] Exclude subdomains by DNS answers, from a file
